### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by rzats** [snowplow-incubator/snowplow-events-manifest#2]
- `BINTRAY_SNOWPLOW_MAVEN_USER`
- `BINTRAY_SNOWPLOW_MAVEN_API_KEY`

**Comment by rzats** [comment]
@alexanderdean these credentials and the Sonatype password from #3 were invalidated due to the repo being renamed. Can you please add them again?

**Comment by alexanderdean** [comment]
I've shared these creds with @BenFradet and @chuwy now - @chuwy should be able to action this now...
